#!/usr/bin/env python
from gi.repository import Gtk
import sys

class Augermatic(Gtk.Window):
    def __init__(self):
        super(Gtk.Window, self).__init__()
        self.connect("delete-event", Gtk.main_quit)
        self.show_all()

if __name__ == '__main__':
    auger = Augermatic()
    Gtk.main()
